var resultado1 = 5 + 3; // Adição
var resultado2 = 10 - 4; // Subtração
var resultado3 = 6 * 7; // Multiplicação
var resultado4 = 15 / 3; // Divisão
var resultado5 = 10 % 3; // Módulo

console.log(resultado1); // Exibe o resultado da adição no console
console.log(resultado2); // Exibe o resultado da subtração no console
console.log(resultado3); // Exibe o resultado da multiplicação no console
console.log(resultado4); // Exibe o resultado da divisão no console
console.log(resultado5); // Exibe o resultado do módulo no console

var cifra = 5;
cifra++; // Incremento
console.log(cifra); // Exibe o valor após o incremento no console

var cifra2 = 8;
cifra2--; // Decremento
console.log(cifra2); // Exibe o valor após o decremento no console