// Um número inteiro
let numero = 550;
console.log(numero);

// Uma string de texto
let texto = "Olá, mundo!";
console.log(texto);

// Um valor booleano verdadeiro
let verdadeiro = true;

// Um valor booleano falso
let falso = false;
console.log(verdadeiro);
console.log(falso);

// Uma variável indefinida
let indefinido;
console.log(indefinido);

// Um valor nulo
let nulo = null;
console.log(nulo);

// Um símbolo descritivo
const emblema = Symbol('Lorem ipsum');
console.log(emblema);